data:
  raw: data/interim/iris.pq
  features: data/processed/iris.pq
  hp_search: data/processed/hp_search.csv

model:
  target: target
  features:
    - sepal_length
    - sepal_width
    - petal_length
    - petal_width
    - sepal_area
    - petal_area
  test_size: 0.25

mlflow:
  experiment_name: iris-classifier
  model_file_path: sklearn_classifier
